spring.application.name=backend
frontend.url=http://localhost:5173

# We use Postgres
spring.datasource.driverClassName=org.postgresql.Driver
# Needed for Postgres to correctly create the database schema
spring.jpa.generate-ddl=true
# Specify the location of the docker file
spring.docker.compose.file=devops/compose.dev.yml
